import streamlit as st
import pandas as pd

# Comprehensive enterprise marketing KPI definitions
KPI_DEFINITIONS = {
    "Spend": {
        "name": "Spend (Ad Spend)",
        "definition": "Total monetary cost incurred across paid advertising channels.",
        "formula": "SUM(spend)",
        "source_system": "Google Ads / Meta Ads / LinkedIn Ads",
        "source_table": "paid_media_daily / campaign_performance",
        "source_field": "spend",
        "aggregation": "SUM(spend)",
        "scope": "Paid Media campaigns across selected period",
        "currency": "USD ($) / INR (₹)",
        "attribution_basis": "Channel billing reporting",
        "exclusions": "Agency management fees, organic traffic cost",
        "refresh_cadence": "Daily / 24h",
        "format": "currency"
    },
    "Revenue": {
        "name": "Revenue (Conversion Value)",
        "definition": "Gross attributed value of conversions resulting directly from marketing campaigns.",
        "formula": "SUM(conversion_value)",
        "source_system": "Paid Media Ad Networks / GA4 Analytics",
        "source_table": "paid_media_daily (conversion_value) / campaign_performance (revenue)",
        "source_field": "conversion_value / revenue",
        "aggregation": "SUM(conversion_value)",
        "scope": "Attributed conversion events",
        "currency": "USD ($) / INR (₹)",
        "attribution_basis": "Platform attribution / Last Click",
        "exclusions": "Offline CRM adjustments (unconnected), refunds",
        "refresh_cadence": "Daily / 24h",
        "format": "currency"
    },
    "Conversions": {
        "name": "Conversions",
        "definition": "Total volume of completed macro-goal actions (purchases, signups, transactions).",
        "formula": "SUM(conversions)",
        "source_system": "Paid Media Ad Networks / GA4 Analytics",
        "source_table": "paid_media_daily / campaign_performance / ga4_daily_channel",
        "source_field": "conversions",
        "aggregation": "SUM(conversions)",
        "scope": "All tracked primary goals",
        "currency": "Count",
        "attribution_basis": "Platform attribution / Last Click",
        "exclusions": "Duplicate submission events, spam bot traffic",
        "refresh_cadence": "Daily / 24h",
        "format": "integer"
    },
    "ROAS": {
        "name": "ROAS (Return on Ad Spend)",
        "definition": "Attributed revenue generated for every dollar/unit of advertising spend.",
        "formula": "Attributed Revenue / Ad Spend",
        "source_system": "Paid Media / Campaign Performance Analytics",
        "source_table": "paid_media_daily / campaign_performance",
        "source_field": "conversion_value, spend",
        "aggregation": "SUM(conversion_value) / NULLIF(SUM(spend), 0)",
        "scope": "Paid Media campaigns",
        "currency": "Ratio (x)",
        "attribution_basis": "Last Click attribution window",
        "exclusions": "Organic conversions, unpaid channels",
        "refresh_cadence": "Daily / 24h",
        "format": "multiplier"
    },
    "ROI": {
        "name": "ROI (Return on Investment %)",
        "definition": "Net profitability percentage generated by advertising campaigns.",
        "formula": "((Attributed Revenue - Ad Spend) / Ad Spend) * 100",
        "source_system": "Marketing Analytical Layer",
        "source_table": "paid_media_daily / campaign_performance",
        "source_field": "conversion_value, spend",
        "aggregation": "((SUM(conversion_value) - SUM(spend)) / NULLIF(SUM(spend), 0)) * 100",
        "scope": "Paid Media performance",
        "currency": "Percentage (%)",
        "attribution_basis": "Last Click",
        "exclusions": "Fixed overheads, agency retainer fees",
        "refresh_cadence": "Daily / 24h",
        "format": "percentage"
    },
    "CTR": {
        "name": "CTR (Click-Through Rate)",
        "definition": "Percentage of ad impressions that resulted in a user click.",
        "formula": "(Total Clicks / Total Impressions) * 100",
        "source_system": "Google Ads / Meta Ads / LinkedIn Ads / GSC",
        "source_table": "paid_media_daily / gsc_daily_queries",
        "source_field": "clicks, impressions",
        "aggregation": "(SUM(clicks) / NULLIF(SUM(impressions), 0)) * 100",
        "scope": "Paid media ads & Search Console queries",
        "currency": "Percentage (%)",
        "attribution_basis": "Direct interaction",
        "exclusions": "Invalid click traffic filtered by platforms",
        "refresh_cadence": "Daily / 24h",
        "format": "percentage"
    },
    "CPC": {
        "name": "CPC (Cost per Click)",
        "definition": "Average advertising spend required to acquire a single user click.",
        "formula": "Total Spend / Total Clicks",
        "source_system": "Paid Media Platforms",
        "source_table": "paid_media_daily / campaign_performance",
        "source_field": "spend, clicks",
        "aggregation": "SUM(spend) / NULLIF(SUM(clicks), 0)",
        "scope": "Paid Media campaigns",
        "currency": "USD ($) / INR (₹)",
        "attribution_basis": "Ad network billing",
        "exclusions": "Impressions without clicks",
        "refresh_cadence": "Daily / 24h",
        "format": "currency_precise"
    },
    "CPM": {
        "name": "CPM (Cost per Mille / Thousand Impressions)",
        "definition": "Cost to deliver 1,000 ad impressions to target audiences.",
        "formula": "(Total Spend / Total Impressions) * 1,000",
        "source_system": "Paid Media Platforms",
        "source_table": "paid_media_daily / campaign_performance",
        "source_field": "spend, impressions",
        "aggregation": "(SUM(spend) / NULLIF(SUM(impressions), 0)) * 1000",
        "scope": "All paid media campaigns",
        "currency": "USD ($) / INR (₹)",
        "attribution_basis": "Ad delivery metric",
        "exclusions": "Unrendered impressions",
        "refresh_cadence": "Daily / 24h",
        "format": "currency_precise"
    },
    "CPA": {
        "name": "CPA (Cost per Acquisition / Conversion)",
        "definition": "Average advertising cost incurred to produce one completed conversion.",
        "formula": "Total Spend / Total Conversions",
        "source_system": "Paid Media / Marketing Analytical Layer",
        "source_table": "paid_media_daily / campaign_performance",
        "source_field": "spend, conversions",
        "aggregation": "SUM(spend) / NULLIF(SUM(conversions), 0)",
        "scope": "Campaigns with tracked conversions",
        "currency": "USD ($) / INR (₹)",
        "attribution_basis": "Last Click attribution",
        "exclusions": "Micro-conversions (page views, scroll depth)",
        "refresh_cadence": "Daily / 24h",
        "format": "currency_precise"
    },
    "CPL": {
        "name": "CPL (Cost per Lead)",
        "definition": "Average advertising cost to acquire a prospect contact or lead form submission.",
        "formula": "Total Spend / Total Leads",
        "source_system": "Paid Media Platforms (Lead Gen)",
        "source_table": "paid_media_daily / campaign_performance",
        "source_field": "spend, leads",
        "aggregation": "SUM(spend) / NULLIF(SUM(leads), 0)",
        "scope": "Lead generation campaigns",
        "currency": "USD ($) / INR (₹)",
        "attribution_basis": "Platform lead form completion",
        "exclusions": "E-commerce purchase only campaigns with zero leads",
        "refresh_cadence": "Daily / 24h",
        "format": "currency_precise"
    },
    "Sessions": {
        "name": "Sessions",
        "definition": "Total volume of user browsing sessions initiated on the website.",
        "formula": "SUM(sessions)",
        "source_system": "Google Analytics 4 (GA4)",
        "source_table": "ga4_daily_channel",
        "source_field": "sessions",
        "aggregation": "SUM(sessions)",
        "scope": "Website traffic across all channels",
        "currency": "Count",
        "attribution_basis": "Session-start event (GA4 standard 30-min window)",
        "exclusions": "Internal team traffic filtered in GA4",
        "refresh_cadence": "Daily / 24h",
        "format": "integer"
    },
    "Engagement Rate": {
        "name": "Engagement Rate",
        "definition": "Percentage of sessions that were engaged sessions (lasted 10+ seconds, had 2+ page views, or a conversion).",
        "formula": "(SUM(engaged_sessions) / SUM(sessions)) * 100",
        "source_system": "Google Analytics 4 (GA4)",
        "source_table": "ga4_daily_channel",
        "source_field": "engaged_sessions, sessions, engagement_rate",
        "aggregation": "(SUM(engaged_sessions) / NULLIF(SUM(sessions), 0)) * 100",
        "scope": "All GA4 tracked web sessions",
        "currency": "Percentage (%)",
        "attribution_basis": "GA4 engagement model",
        "exclusions": "Bounced or instant drop-off sessions (<10s)",
        "refresh_cadence": "Daily / 24h",
        "format": "percentage"
    },
    "Budget Utilization": {
        "name": "Budget Utilization (%)",
        "definition": "Percentage of approved marketing budget that has been consumed by actual spend.",
        "formula": "(Actual Spend / Approved Budget) * 100",
        "source_system": "Marketing Budgeting Layer",
        "source_table": "campaign_performance / paid_media_daily",
        "source_field": "spend, approved_budget, budget_utilization",
        "aggregation": "(SUM(spend) / NULLIF(SUM(approved_budget), 0)) * 100",
        "scope": "Active campaign budgets",
        "currency": "Percentage (%)",
        "attribution_basis": "Budget reconciliation",
        "exclusions": "Campaigns with unallocated/zero budgets",
        "refresh_cadence": "Daily / 24h",
        "format": "percentage"
    },
    "Pacing Variance": {
        "name": "Pacing Variance",
        "definition": "Deviation between actual spend and the expected spend-to-date schedule.",
        "formula": "Actual Spend - Expected Spend to Date",
        "source_system": "Marketing Budget Allocation System",
        "source_table": "paid_media_daily",
        "source_field": "pacing_variance",
        "aggregation": "SUM(pacing_variance)",
        "scope": "Campaigns with scheduled flight dates",
        "currency": "USD ($) / INR (₹)",
        "attribution_basis": "Linear daily pacing",
        "exclusions": "Open-ended evergreen campaigns without end date",
        "refresh_cadence": "Daily / 24h",
        "format": "currency"
    },
    "Forecast Spend": {
        "name": "Forecast Spend",
        "definition": "Projected total campaign expenditure by end-of-flight based on current burn rate.",
        "formula": "Actual Spend + (Daily Burn Rate * Remaining Days)",
        "source_system": "Budget Pacing Forecasting Model",
        "source_table": "paid_media_daily",
        "source_field": "forecast_spend",
        "aggregation": "SUM(forecast_spend)",
        "scope": "Flighted campaigns",
        "currency": "USD ($) / INR (₹)",
        "attribution_basis": "Run-rate projection",
        "exclusions": "Paused campaigns",
        "refresh_cadence": "Daily / 24h",
        "format": "currency"
    },
    "Average Position": {
        "name": "Average Position",
        "definition": "Mean organic search ranking position of pages in Google Search result pages.",
        "formula": "Weighted Average Position by Impressions",
        "source_system": "Google Search Console (GSC)",
        "source_table": "gsc_daily_queries",
        "source_field": "average_position",
        "aggregation": "AVG(average_position)",
        "scope": "Tracked organic Google search queries",
        "currency": "Rank (Lower is better)",
        "attribution_basis": "Search engine SERP rank",
        "exclusions": "Queries outside Top 100",
        "refresh_cadence": "Daily / 24h",
        "format": "decimal"
    }
}

def get_kpi_def(kpi_key: str):
    """Retrieve definition dictionary for a given KPI, or fallback to sensible default."""
    for key, val in KPI_DEFINITIONS.items():
        if key.lower() in kpi_key.lower() or kpi_key.lower() in key.lower():
            return val
    return {
        "name": kpi_key,
        "definition": "Standard marketing performance metric.",
        "formula": "Calculated from aggregated dataset",
        "source_system": "Marketing Database",
        "source_table": "paid_media_daily / campaign_performance",
        "source_field": "Not available in current dataset.",
        "aggregation": "SUM or AVG",
        "scope": "Current selection",
        "currency": "Standard",
        "attribution_basis": "Last Click",
        "exclusions": "None",
        "refresh_cadence": "Daily",
        "format": "standard"
    }

def render_kpi_popover(kpi_key: str):
    """Renders a small info icon popover displaying official KPI dictionary metadata."""
    meta = get_kpi_def(kpi_key)
    with st.popover("ℹ️", use_container_width=False):
        st.markdown(f"### 📖 {meta['name']}")
        st.markdown(f"**Definition:** {meta['definition']}")
        st.divider()
        col1, col2 = st.columns(2)
        with col1:
            st.markdown(f"**Formula:** `{meta['formula']}`")
            st.markdown(f"**Source System:** {meta['source_system']}")
            st.markdown(f"**Source Table:** `{meta['source_table']}`")
            st.markdown(f"**Source Field:** `{meta['source_field']}`")
        with col2:
            st.markdown(f"**Aggregation:** `{meta['aggregation']}`")
            st.markdown(f"**Scope:** {meta['scope']}")
            st.markdown(f"**Currency / Unit:** {meta['currency']}")
            st.markdown(f"**Attribution Basis:** {meta['attribution_basis']}")
        st.caption(f"Exclusions: {meta['exclusions']} | Refresh: {meta['refresh_cadence']}")

def get_dictionary_dataframe():
    """Returns a pandas DataFrame representation of the KPI dictionary for table display."""
    rows = []
    for k, v in KPI_DEFINITIONS.items():
        rows.append({
            "KPI": v["name"],
            "Definition": v["definition"],
            "Formula": v["formula"],
            "Source System": v["source_system"],
            "Source Table": v["source_table"],
            "Source Field": v["source_field"],
            "Aggregation": v["aggregation"],
            "Currency / Unit": v["currency"],
            "Attribution Basis": v["attribution_basis"],
            "Refresh Cadence": v["refresh_cadence"]
        })
    return pd.DataFrame(rows)
